export const MAPS_LIST_REQUEST = "MAPS_LIST_REQUEST";
export const MAPS_FAILURE = "MAPS_FAILURE";
export const MAPS_SUCCESS = "MAPS_SUCCESS";
export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const BOOK_SUCCESS = "BOOK_SUCCESS";
export const BOOK_FAILURE = "BOOK_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";
